name: Build Windows EXE

on:
  push:
    paths:
      - 'sx/**.cpp'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'sx/**.cpp'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compile C++ files
      run: |
        g++ sx/*.cpp -o sx_program.exe

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: sx_program
        path: sx_program.exe
